[package]
name = "DungeonCrawler"
version = "0.1.3"
edition = "2018"
authors = ["Eddie Ho"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
